version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 18
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login  --no-include-email --region us-east-2)
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java"
      - cd pension
      - mvn -DskipTests clean package
      - docker build -t ij027-pod5-process-pension-registry:latest .
      - docker tag ij027-pod5-process-pension-registry:latest 941516478045.dkr.ecr.us-east-2.amazonaws.com/ij027-pod5-process-pension-registry:latest

  post_build:
    commands:
      - echo "Post_build"
      - docker push 941516478045.dkr.ecr.us-east-2.amazonaws.com/ij027-pod5-process-pension-registry:latest
      - printf '[{"name":"ij027-pod5-pension-container","imageUri":"%s"}]' 941516478045.dkr.ecr.us-east-2.amazonaws.com/ij027-pod5-process-pension-registry:latest > taskdefinition.json
      - cat taskdefinition.json

artifacts:
  files:
    - pension/taskdefinition.json